name: stephanie-insight
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- jupyter
- jupyterlab
- conda
- scikit-learn
- scipy
- pandas
- numpy
- matplotlib
- seaborn
- dash=0.35.2
- dash-html-components
- dash-core-components
- scikit-learn
- black
- mypy
- flake8
- pylint
